config/routes.rb
FileToDb::Application.routes.draw do
  root 'entities#index'

  get '/total_scale' => 'entities#total_scale', as: :total_scale
  get '/file_scale' => 'entities#file_scale', as: :file_scale
  get '/total_file_scale' => 'entities#total_file_scale', as: :total_file_scale
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  include Operator

  COLUMNS = (1..32).map { |column_nomber| "column_#{column_nomber}".to_sym }
  FILENAME_SIZE = 4

  COLUMNS.each { |column| validates column, presence: true }

  validates :s, presence: true
  validates :x, presence: true
  validates :l, presence: true
  validates :w, presence: true
end

app/models/extended_entity.rb
class ExtendedEntity < ActiveRecord::Base
  include Operator

  COLUMNS = (1..32).map { |column_nomber| "column_#{column_nomber}".to_sym }
  FILENAME_SIZE = 7

  COLUMNS.each { |column| validates column, presence: true }

  validates :s, presence: true
  validates :x, presence: true
  validates :l, presence: true
  validates :w, presence: true
end

app/models/identificator.rb
class Identificator < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
  end

  def total_file_scale
    file_name = params[:file_name]

    return if file_name.blank?

    file_hash = {s: file_name[0],
                 x: file_name[1],
                 l: file_name[2],
                 w: file_name[3]}

    @total_file_scale = Entity.total_file_scale(file_hash)
  end

  def file_scale
    file_name = params[:file_name]

    return if file_name.blank?

    file_hash = {s: file_name[0],
                 x: file_name[1],
                 l: file_name[2],
                 w: file_name[3]}

    @file_scale = Entity.file_scale(file_hash)
  end

  def total_scale
    @total_scale = Entity.total_scale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_controller_helper.rb
module EntitiesControllerHelper
end

app/views/entities/file_scale.html.haml
%table
  %body
    %tr
      - Entity::COLUMNS.each do |column|
        %th
          = column
    %tr
      - Entity::COLUMNS.each do |column|
        %td
          = @file_scale[column]

app/views/entities/index.html.haml
- submit = 'Так точно'

= label_tag :file_name, 'Введите название файла для нахождения размаха по столбцам'
= form_tag(file_scale_url, method: :get) do
  = text_field_tag :file_name
  = submit_tag submit

= label_tag :file_name, 'Введите название файла для нахождения размаха'
= form_tag(total_file_scale_url, method: :get) do
  = text_field_tag :file_name
  = submit_tag submit

= label_tag :file_name, 'Нажмите для нахождения глобального размаха по координатам'
= form_tag(total_scale_url, method: :get) do
  = submit_tag submit

app/views/entities/total_file_scale.html.haml
= @total_file_scale

app/views/entities/total_scale.html.haml
%table
  %body
    %tr
      - Entity::COLUMNS.each do |column|
        %th
          = column
    %tr
      - Entity::COLUMNS.each do |column|
        %td
          = @total_scale[column]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileToDb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>